[package]
name = "vetra-core"
version = "0.1.0"
description = "Core program for VETRA - Decentralized AI Model Validation Platform"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/vetra-protocol/vetra"
documentation = "https://docs.vetra.io"
readme = "README.md"

[features]
default = ["devnet"]
devnet = []
testnet = []
mainnet = []
no-entrypoint = []

[dependencies]
solana-program = "1.17"
borsh = "0.10.3"
thiserror = "1.0"
num-derive = "0.4"
num-traits = "0.2"
arrayref = "0.3.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21"
sha2 = "0.10"
hmac = "0.12"
rand = "0.8"
log = "0.4"

# AI/ML related dependencies
tract-onnx = "0.20"  # ONNX model support
tokenizers = "0.15"  # For tokenization in AI model processing
rust-bert = "0.21"   # For transformer model operations

[dev-dependencies]
solana-program-test = "1.17"
solana-sdk = "1.17"
tokio = { version = "1.35", features = ["full"] }
anyhow = "1.0"
mockall = "0.12"

[lib]
name = "vetra_core"
crate-type = ["cdylib", "lib"]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1